language: python
python:
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  sudo apt install wine-stable && wine python lichess-bot.py -u
